name: alanc-crapi-k8s
runtime:
  name: python
  options:
    toolchain: poetry
description: A Python program to deploy a Kubernetes cluster on AWS
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-aws-python
